version: "3.9"

services:
  category_products:
    container_name: category_products
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_USER=victor
      - DB_PASSWORD=Victor.95
      - DB_HOST=db
      - DB=products_management
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=victor
      - POSTGRES_PASSWORD=Victor.95
      - POSTGRES_DB=products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U victor -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
